FROM jenkins

# Become root to install via apt.
USER root

# Install php.
RUN apt-get update
RUN apt-get install curl php-cli php-mbstring git unzip

# Drop back to jenkins
USER jenkins

# Install plugins.
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt
